---
title: "Data Science Homework 5"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

### Problem 1

```{r importing and tidying data, message = FALSE}
file_names <- list.files("./data/", full.names = TRUE)

df <- file_names %>% 
  map(read_csv)

for (i in 1:20) {
  if (i < 11) {
    df[[i]] <- df[[i]] %>% 
    mutate(arm = "Control", 
           study_id = i)
  } else if (i > 10) {
    df[[i]] <- df[[i]] %>% 
      mutate(arm = "Experimental", 
             study_id = i - 10)
  }
}

df <- bind_rows(df) %>% 
  gather(key = week, value = obs, week_1:week_8) %>% 
  arrange(week, study_id) %>% 
  separate(col = week, into = c("delete", "week")) %>% 
  select(-delete)
```

```{r spaghetti plot, fig.align = "center", out.width = "75%", dpi = 300}
df %>% 
  mutate(week = as.double(week), 
         study_id = as.character(study_id)) %>% 
  group_by(arm, study_id) %>% 
  ggplot(aes(x = week, y = obs, color = arm, type = study_id)) + 
    geom_line() + 
  theme_bw() + 
  labs(title = "Trend in observations across weeks for each\n participant stratified by study arm",
       x = "Week", 
       y = "Observation") + 
  viridis::scale_color_viridis(name = "Study arm",
                               discrete = TRUE) + 
  theme(legend.position = "bottom", 
        legend.direction = "horizontal", 
        legend.box.spacing = unit(0.05, "cm"),
        plot.title = element_text(size = 11))
```


### Problem 2

```{r importing data, message = FALSE}
murder <- 
  read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv") %>% 
  janitor::clean_names()
```

```{r creating dataset with unsolved and total}
murder <- murder %>% 
  unite("city_state", c("city", "state"), sep = ", ")

unsolved <- murder %>% 
  group_by(city_state) %>% 
  filter(disposition %in% c("Closed without arrest", 
                            "Open/No arrest")) %>% 
  summarize(unsolved = n()) 

total_cases <- murder %>% 
  group_by(city_state) %>%
  summarize(total = n())

all_cases <- left_join(unsolved, total_cases, by = "city_state")
```

```{r fig.align = "center", fig.height = 8, out.width = "80%", dpi = 300}
unsolved %>% 
  mutate(city_state = fct_reorder(city_state, unsolved)) %>% 
  ggplot(aes(x = city_state, y = unsolved)) + 
  geom_bar(stat = "identity", fill = "#A35E60") + 
  coord_flip() + 
  labs(title = "Number of unsolved homicides in 50 major US cities", 
       y = "Number of unsolved homicides", 
       x = "City") + 
  theme_bw() + 
  theme(plot.title = element_text(size = 12))
```

```{r proportion confidence interval iterations, fig.align = "center", out.width = "75%", fig.height = 7, dpi = 300}
prop_unsolved <- function(df) {

  ci_unsolved <- prop.test(df$unsolved, df$total)
  
  broom::tidy(ci_unsolved) %>% 
    select(estimate, conf.low, conf.high)
}

city_nest <- nest(all_cases, unsolved:total)

# prop_unsolved(city_nest$data[[1]])
# map(city_nest$data, prop_unsolved)

unsolved_ci <- city_nest %>% 
  mutate(prop_unsolved = map(data, prop_unsolved)) %>% 
  unnest() %>% 
  rename(conf_low = conf.low, 
         conf_high = conf.high)

unsolved_ci %>% 
  mutate(city_state = fct_reorder(city_state, estimate)) %>% 
  ggplot(aes(x = city_state, y = estimate)) + 
  geom_point(color = "#A35E60") + 
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high)) + 
  coord_flip() + 
  labs(title = "Proportion of unsolved cases in 50 major US cities", 
       y = "Proportion of unsolved cases", 
       x = "City") + 
  theme_classic() 
```















